### ISSUE TITLE
Review slade-admin tree styling

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate-theme#5]
We needed the expander arrows to be visible and work in some of the settings trees, while the People navtree had extra logic that would expand child nodes on select, these other trees don't have that (yet at least) and can't be expanded without the arrow visible.

These changes were made so that trees that has useArrows: true set would get working arrows again. This may make them ugly and might make the people navtree ugly (with useArrows off it just has [+] buttons instead of arrows). We need to find a better looks for these and way to hide them on some trees. Maybe make something like an optional 'has-expandonselect' class we can put on trees like the navtree.

**Comment by themightychris** [comment]
See 230750ca5d749fc2fdbc30a9d15c0b5ee7e796bd and 5d272a07a7803748a2f6b28edf842536006330ac

**Comment by ryon** [comment]
@themightychris Going forward, `useArrows` and `lines` will be off by default, and plus/minus expanders have shiny new graphics. See https://github.com/SlateFoundation/slate-admin/issues/46#issuecomment-139682598
